### PR TITLE
Add "Deploy on Zeabur" tutorial in README file

### PR DESCRIPTION
**Pull request by MichaelYuhe**
Hey, I've found your project in V2EX, but it's demo link seems broken.
So I wanna recommend my product Zeabur as an option for users to selfhost this project more easily!
Here is the final link: [chatgpt-next.zeabur.app](https://chatgpt-next.zeabur.app/)

### CODE REVIEW

**Comment by xcatliu** [comment]
LGTM

**Comment by xcatliu** [comment]
@MichaelYuhe  Can I put this link https://chatgpt-next.zeabur.app/ in the readme?

**Comment by MichaelYuhe** [comment]
Sure!

**Comment by xcatliu** [comment]
The reason demo link seems broken is that I forgot to remove the default godaddy dns record "Parked"

This should fixed now https://chatgpt-next.com

**Comment by xcatliu** [comment]
@MichaelYuhe Is there a "Deploy to   Zeabur" button to one-click-to-deploy?

**Comment by MichaelYuhe** [comment]
> @MichaelYuhe Is there a "Deploy to   Zeabur" button to one-click-to-deploy from a template?

We are working on that.

**Comment by xcatliu** [comment]
I am looking forward to this feature. We can put the button here
image

**Comment by MichaelYuhe** [comment]
> I am looking forward to this feature. We can put the button here
> image

This is what we are going to do in the next development cycle! Thanks for feedback, we will keep improving Zeabur.

**Pull request merged**
